[versions]
activityComposeVersion = "1.7.2"
agp = "8.7.2"
androidxComposeBom = "2024.12.01"
androidxComposeMaterial3Material3 = "1.0.0"
androidxComposeMaterial3Material32 = "1.2.1"
androidxComposeMaterial3Material33 = "1.3.1"
androidxComposeUiUi = "1.5.1"
androidxMaterial = "1.5.0"
androidxMaterial3 = "1.1.0-beta01"
androidxMaterial3Version = "1.0.0-alpha04"
androidxNavigationCompose = "2.7.2"
animatedNavigationBar = "1.0.0"
animation = "1.7.6"
bcrypt = "0.9.0"
coil = "2.7.0"
coilCompose = "2.7.0"
composeBomVersion = "2024.01.00"
khttp = "1.0.0"
kotlin = "2.0.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.9.3"
composeBom = "2024.04.01"
material = "1.7.6"
#material3 = "1.3.1"
material3 = "1.2.1"
material3Version = "1.2.0-alpha01"
materialVersion = "1.12.0"
microsoftMsal = "2.0.8"
mongodbDriverKotlinCoroutine = "4.1.0"
mongodbDriverSync = "4.11.1"
mongodbRealm = "10.11.0"
msal = "5.0.0"
navigationCompose = "2.8.5"
navigationComposeVersion = "2.6.0"
navigationRuntimeKtx = "2.8.4"
benchmarkMacro = "1.3.3"
realmAndroidLibrary = "10.11.0"
sdk = "1.9.0"
streamVideoAndroidCompose = "1.0.15"
streamVideoAndroidUiCompose = "1.2.0"
streamVideoAndroidUiComposeVersion = "1.0.15"
ui = "1.7.6"
material3Desktop = "1.3.1"
material3Android = "1.3.1"
firebaseFirestoreKtx = "25.1.2"
runtimeLivedata = "1.7.7"
firebaseCommonKtx = "21.0.0"
firebaseStorageKtx = "21.0.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose" }
androidx-activity-compose-v172 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-animation = { module = "androidx.compose.animation:animation", version.ref = "animation" }
androidx-compose-bom-v20240100 = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-compose-bom-v20241201 = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material-material = { module = "androidx.compose.material:material" }
androidx-compose-material-material2 = { module = "androidx.compose.material:material" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-ui-v151-x2 = { module = "androidx.compose.ui:ui", version.ref = "androidxComposeUiUi" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material" }
androidx-material-v150 = { module = "androidx.compose.material:material", version.ref = "androidxMaterial" }
androidx-material3-v100 = { module = "androidx.compose.material3:material3", version.ref = "androidxComposeMaterial3Material3" }
androidx-material3-v100alpha04 = { module = "androidx.compose.material3:material3", version.ref = "androidxMaterial3Version" }
androidx-material3-v110beta01 = { module = "androidx.compose.material3:material3", version.ref = "androidxMaterial3" }
androidx-material3-v120alpha01 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
androidx-material3-v121 = { module = "androidx.compose.material3:material3", version.ref = "androidxComposeMaterial3Material32" }
androidx-material3-v131 = { module = "androidx.compose.material3:material3", version.ref = "androidxComposeMaterial3Material33" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-compose-v260 = { module = "androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }
androidx-navigation-compose-v272 = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationCompose" }
animated-navigation-bar = { module = "com.exyte:animated-navigation-bar", version.ref = "animatedNavigationBar" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
getstream-stream-video-android-ui-compose = { module = "io.getstream:stream-video-android-ui-compose", version.ref = "streamVideoAndroidUiCompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro", version.ref = "benchmarkMacro" }
khttp = { module = "khttp:khttp", version.ref = "khttp" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
mongodb-driver-kotlin-coroutine = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "mongodbDriverKotlinCoroutine" }
mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodbDriverSync" }
mongodb-realm = { module = "org.mongodb:mongodb-realm", version.ref = "mongodbRealm" }
msal = { module = "com.microsoft.identity.client:msal", version.ref = "msal" }
navigation-compose = { module = "androidx.navigation:navigation-compose" }
realm-android-library = { module = "io.realm:realm-android-library", version.ref = "realmAndroidLibrary" }
sdk = { module = "com.zoom:sdk", version.ref = "sdk" }
stream-chat-android-client = { module = "io.getstream:stream-chat-android-client" }
stream-chat-android-compose = { module = "io.getstream:stream-chat-android-compose" }
stream-chat-android-offline = { module = "io.getstream:stream-chat-android-offline" }
stream-chat-android-ui-components = { module = "io.getstream:stream-chat-android-ui-components" }
stream-video-android-compose = { module = "io.getstream:stream-video-android-compose", version.ref = "streamVideoAndroidCompose" }
stream-video-android-ui-compose = { module = "io.getstream:stream-video-android-ui-compose" }
stream-video-android-ui-compose-v1015 = { module = "io.getstream:stream-video-android-ui-compose", version.ref = "streamVideoAndroidUiComposeVersion" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-material3-desktop = { group = "androidx.compose.material3", name = "material3-desktop", version.ref = "material3Desktop" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebaseCommonKtx" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

